# Generated by Django 6.0.4 on 2026-05-03 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('requirements_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementform',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_forms', to='jobs.job'),
        ),
    ]
