# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contract_template',
            field=models.TextField(blank=True, default=''),
        ),
    ]
