# Generated by Django 6.0.4 on 2026-06-06 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0004_job_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLPResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField(default=list)),
                ('clusters', models.JSONField(default=list)),
                ('duplicates', models.JSONField(default=list)),
                ('priorities', models.JSONField(default=dict)),
                ('low_quality_requirements', models.JSONField(default=list)),
                ('mcq_statistics', models.JSONField(default=dict)),
                ('statistics', models.JSONField(default=dict)),
                ('spelling_corrections', models.JSONField(default=dict)),
                ('polished_requirements', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nlp_result', to='jobs.job')),
            ],
        ),
    ]
