# Generated by Django 6.0.4 on 2026-05-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlpresult',
            name='low_quality_requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='nlpresult',
            name='mcq_statistics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='nlpresult',
            name='statistics',
            field=models.JSONField(default=dict),
        ),
    ]
