# Generated by Django 6.0.4 on 2026-06-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_engine', '0003_nlpresult_spelling_corrections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlpresult',
            name='polished_requirements',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
